### ISSUE TITLE
Usr merge and password reset

### ISSUE THREAD

**Issue by deltacrux** [bravecollective/core#110]
Due to my lack of reading comprehension skills and the consumption of alcohol, I need to have the accounts "Matthaus Beringer" and "mberinger" merged.  Additionally, if the password of the merged account could be reset that would rock.

Sorry for the confusion and my lack of attention.

**Comment by TriumvirateRhade** [comment]
This was previously submitted to the admin for an account merge.

**Comment by deltacrux** [comment]
Understood.  I'll work on other characters.  Thank you.

**Comment by deltacrux** [comment]
Disregard and close.  Dropped corp.
