### ISSUE TITLE
Serinus access to bravecollective.github.io & pull request

### ISSUE THREAD

**Issue by Serinus1** [bravecollective/core#124]
I'd like to be able to accept pull requests for this project.  I'd like to submit the following as evidence: https://github.com/Serinus1/bravecollective.github.io/network

I'm perfectly happy to give it up in the future, hopefully to someone less busy than Lquid!  And of course you know you'll always still have veto power anyway and can revoke control at any time.  This just saves us the trouble of me pinging you for pull requests, and helps me in recruiting people to create content.

There's also a pull request that needs to be accepted, please!  

https://github.com/bravecollective/bravecollective.github.io/pulls

**Comment by jboning** [comment]
refiled on the website project, closing this issue here
