### ISSUE TITLE
API access to non-primary characters

### ISSUE THREAD

**Issue by jboning** [bravecollective/core#131]

**Comment by Acidity** [comment]
This already exists I believe... Only thing is that applications have no way to know which characters are owned by the same core account and as such have to treat each character as a separate user.

**Comment by paxswill** [comment]
Couldn't this be resolved by [allowing access](https://github.com/bravecollective/core/blob/develop/brave/core/api/eve.py#L34) to the [account.Characters](http://wiki.eve-id.net/APIv2_Account_Characters_XML) API endpoint? The security implications of allowing access to that endpoint seem fairly minor (and an application still has to have that access mask). Really, I'm not having a whole lot of luck thinking of many application uses for the account.\* calls besides Characters.

**Comment by mglinski** [comment]
No, then you would only see characters on the account whose API key was selected for use on the proxy. There needs to be a way to select multiple characters to allow access to on an authorized app and a dedicated core endpoint for getting all those characters' /info calls at once for an authorized app.
