### ISSUE TITLE
Enforce password strength requirements on reset passwords.

### ISSUE THREAD

**Issue by Acidity** [bravecollective/core#139]
Passwords reset using the new email system do not have strength requirements like when users sign up initially.

**Comment by Acidity** [comment]
Should be fixed by PR #142, still needs to be tested.

**Comment by jboning** [comment]
Do you need to test this still, or is this OK to be closed?

**Comment by Acidity** [comment]
Well I've never personally tested it, but looking at the code I imagine it should be fine. I just don't have a mail server on my test machine to test it with.

**Comment by jboning** [comment]
Gonna go ahead and close this then.
