### ISSUE TITLE
Revamp UI to allow for error messages.

### ISSUE THREAD

**Issue by Acidity** [bravecollective/core#145]
Instead of merely a red X, we need a way for the server to communicate errors in forms, etc. to the user. Preferably allow for the server to specify individual fields to have error messages applied to it. Could potentially use the validation.js found in brave/core/public/js/. See brave/core/account/template/signup.html for example usage.

**Comment by jboning** [comment]
The signup page does a decent job of giving feedback on errors. Maybe it has some patterns we can abstract out or reuse?

**Comment by Acidity** [comment]
The signup page is pretty abstracted, but off the top of my head I feel like it's only good for certain things, and it still requires both client-side and server-side checks (though the client-side ones are actually done server-side). It'll fix the lack of communication problem, but not really the "double work" problem. That said I definitely think it's our best bet for a starting point; I'll definitely keep thinking on a way to get this fixed because it's a pretty major issue.
