### ISSUE TITLE
settings form styling is weirdly inconsistent

### ISSUE THREAD

**Issue by jboning** [bravecollective/core#151]
![](https://dl.dropbox.com/s/d42x6nq1c42z3ke/Screenshot%202014-04-30%2023.30.00.png)

**Comment by Acidity** [comment]
Honestly, no idea what causes this, might be a CSS thing due to the different text types of the fields (password boxes are password, every other one in that picture is just text)..

**Comment by bargulg** [comment]
fixed in #407
