### ISSUE TITLE
Fix the field names in mongodb.

### ISSUE THREAD

**Issue by Acidity** [bravecollective/core#153]
Single character fields make for difficult to read databases, and only serve to make DB Admin's lives more difficult. Will probably require a database migration.

**Comment by jboning** [comment]
How often do you interact with the database directly? All of the times I've needed to touch the database so far, using the python models has been fine.

Also, I'm not a mongo expert, it _may_ be that the space savings of these is meaningful? I'd be surprised if it's too huge, but it would be nice to better understand the impact here.

Even if space is really not an issue, I'm not convinced moving is worthwhile. It feels like the need is low (python models serve to provide usable names) and the cost is high (migrating all the field names will be hella annoying).

**Comment by Acidity** [comment]
I personally spend quite a bit of time interacting with the database manually due to verifying changes went through properly, and temporarily resolving bugs encountered when writing a new feature. I do agree that if we decide to move forward with this that it should be a very low priority.

**Comment by Acidity** [comment]
Not particularly important. Closing.
