### ISSUE TITLE
Verify that the API handling code obeys CCP caching timers.

### ISSUE THREAD

**Issue by Acidity** [bravecollective/core#154]
Explicitly mentioned by CCP at fanfest as a potential cause for #115 (could in fact have been a direct reference to 115, I dunno), but either way we should ensure that we're receiving data from CCP properly.

**Comment by jboning** [comment]
Pretty sure that https://github.com/bravecollective/core/blob/develop/brave/core/util/eve.py#L200 does this correctly

**Comment by jboning** [comment]
looked at the code again and I'm satisfied that it's OK. feel free to reopen if anything points to the contrary
