### ISSUE TITLE
Node.js API Bindings

### ISSUE THREAD

**Issue by amcgregor** [bravecollective/core#16]

**Comment by ghost** [comment]
I'll look into it.

**Comment by amcgregor** [comment]
@DamonGant Assigned.

**Comment by ghost** [comment]
dibs

**Comment by ghost** [comment]
Stuck atm signing requests, see http://stackoverflow.com/questions/20205728/hex-encode-ecdsa-keys-in-node-js

**Comment by ghost** [comment]
I had code for this, afaik you can just use an ECDSA PEM with the crypto.createSign method (even though it's undocumented)

Edit: Nevermind, I used this one. https://github.com/dekz/dcrypt

**Comment by ghost** [comment]
So someone ported cryptocoinjs to work without the DOM. I've written a little wrapper for it (cleaner dependencies/converts node buffers) that I may or may not use as a base for something more convenient that you can just plug into express.

https://github.com/DamonGant/brave-ecdsa

**Comment by amcgregor** [comment]
@DamonGant Nice; that looks like it'll be a great base to start from.  Not much code committed yet, though.  ;P

**Comment by ghost** [comment]
@amcgregor Yeah, took me a while to figure out how browser JS handles buffers, and then another one to figure out ToJSON is in fact ToArray.

That package is good as it is right now, will get to putting some work into an express middleware soon™.

**Comment by amcgregor** [comment]
@DamonGant Not sure about browser support, but I'm _fairly_ certain ECMAScript supports wildcard accessors.  If it does, you can create the same style of API wrapper I did for Python and Lquid did for PHP, allowing arbitrary attribute access to generate dynamic calls into the API.  In Python the following code:

``` python
api.lookup.alliance('Brave Collective')
```

Effectively turns into:

``` python
api.__getattr__('lookup').__getattr__('alliance').__call__('Brave Collective')
```

Which then turns into a URL, with each `__getattr__` simply appending a new path element.

**Comment by ghost** [comment]
It's actually a realtively new feature new in ES6, node has it from 0.8 but needs to be run with -harmony_proxies. Your call if we should use that or promises.

```
if (typeof Proxy == 'undefined') {
    console.log("Proxy is undefined, run node with --harmony_proxies")
    process.exit();
}

var p = Proxy.create({
  get: function(proxy, name) {
    return 'Hello, '+ name;
  }
});

console.log(p.World); // 'Hello World'
```
