### ISSUE TITLE
PHP API Bindings

### ISSUE THREAD

**Issue by amcgregor** [bravecollective/core#17]

**Comment by tiyowan** [comment]
Lquid, you want the front-end team to look into this?

**Comment by mglinski** [comment]
Yea, we are gonna need to do this anyway for the next project. Ill work on writing up some classes to get it working. Assign me pls.

**Comment by amcgregor** [comment]
@mglinski Assigned.

**Comment by mglinski** [comment]
This is now Complete, please close.
https://github.com/bravecollective/php-api
