### ISSUE TITLE
unique index on keys requires database cleanup

### ISSUE THREAD

**Issue by jboning** [bravecollective/core#173]
https://github.com/bravecollective/core/blob/develop/brave/core/key/model.py#L28 Making the index unique means that if there are any duplicate keys, there will be an error when reading from the database (it tries to create the index before reading, and can't).

I fixed this manually in sound's database (there was only one duplicate), but I imagine you all (and anyone else who might be running this software... hi BPA!) will want some better way of dealing with it. Or at the very least a reminder to chase all of these down before updating code....

**Comment by Acidity** [comment]
Perhaps we should create a file in the root directory of this repo with instructions like this every time there's a change that require administrator intervention before an update?

**Comment by Acidity** [comment]
Handled by #191.
