### ISSUE TITLE
lint

### ISSUE THREAD

**Issue by jboning** [bravecollective/core#176]
Setting up a linter will help catch silly bugs before merging. I did all of the work to set lint up for forums but never worked out with draleth what style rules it should enforce. Let's work out rules and I'll commit it there and here.

**Comment by Acidity** [comment]
I'm not very picky about style rules, especially on python since I'm still relatively new to python, so I'll probably defer to your opinions, as long as we keep it consistent. Except for tabs. 4 space tabs only please.

**Comment by Acidity** [comment]
Resolved by #180.
