### ISSUE TITLE
Overhaul Groups and permissions.

### ISSUE THREAD

**Issue by Acidity** [bravecollective/core#178]
This is just a proposal for now:

Ideally, I would like to have applications (and Core itself) determine whether a user is eligible to perform an action or see information, etc. based on separate permissions rather than the groups used now. These permissions, which would be a string of the from "app.highLevelFunction.action" would be set to either true or false, defaulting to false. Groups, rather than being used directly to determine eligibility, would be collections of permissions, so for instance, the "FC" group may have the "jabber.ping" and "timeboard.add" permissions in it, and any user in the group FC would inherit that permission. Permissions and groups should both be able to be individually assigned to users by Core admins as well as automatically added based on admin-defined ACLs.

Rules should be able to both add and revoke permissions. Additionally, rules should have admin set priorites for cases where a conflict arises (see below). When determining whether a user has a certain permission the general order should be: manual individual permissions, manual group permissions, ACL individual permissions, ACL group permissions. (Note, manual and ACL refers to the assignment of the group to the user). Within these categories, rules should be evaluated in order based on their assigned priorities.

Groups should be able to inherit permissions from one or more other groups, with the inheritance also being prioritized for rule assignment (i.e. inherit group A with priority 1, group B with priority 2; all group A permissions evaluated before any group B). Additionally, all group specific permissions should be evaluated before any inherited permissions.

The goal of this system is to provide a relatively simple, easily extendable, customizable system for Core operators to determine who gets which permissions, while removing the burden of having to make specific groups exactly as an application developer named them. The evaluation rules are designed to minimize the number of unintended permissions granted: All manually added permissions trump inherited and ACL granted ones. There should also be a tool (ideally built into the groups/permissions interface) that will evaluate a user for a certain permission (or all permissions), and show where exactly the rule that led to that outcome came from (like a stack trace).

**Comment by jboning** [comment]
I'm going to jump to the bottom first, and go from there.

> The goal of this system is to provide a relatively simple, easily extendable, customizable system for Core operators to determine who gets which permissions, while removing the burden of having to make specific groups exactly as an application developer named them.

I think this is the wrong way to think about it. Applications shouldn't require specific core groups to exist; rather, they should use core groups in a configurable manner. To take a timerboard as an example, imagine it has two levels of permission, "view" and "edit". In the configuration file, the timerboard admin would specify what groups grant these permissions, like "view=brave,blue" and "edit=fc". This way, the application developer specify only the different levels of user access (which is all they really care about; the application admin specifies what groups of users have access to what permissions; and the core admin specifies what users are in what groups. Of course, if no existing groups work for some set of permissions, the core admin and the application admin will have to coordinate on creating a new group, but I don't think that's too terrible.

Note that in this system, a "permission" isn't really a thing as far as core is concerned. The notion of a "permission" only exists in the application, and this notion extends only as far as the application's config file.

> When determining whether a user has a certain permission the general order should be: manual individual permissions, manual group permissions, ACL individual permissions, ACL group permissions. (Note, manual and ACL refers to the assignment of the group to the user).

I don't think there's any need for a manual/ACL distinction; in the current system, "accept character x" is an ACL rule just like any other.

> Groups should be able to inherit permissions from one or more other groups, with the inheritance also being prioritized for rule assignment (i.e. inherit group A with priority 1, group B with priority 2; all group A permissions evaluated before any group B). Additionally, all group specific permissions should be evaluated before any inherited permissions.

I find this description pretty confusing. Being able to express things like "directors have all permissions that diplos have and all permissions that FCs have" is nice, but when combined with negative permissions, I think the usage is going to get extremely confusing extremely fast.

I think that allowing group ACL rules to refer to other groups solves the problem you're looking at in a much clearer way. Using this model, when defining the diplo group, we can include a rule that says "allow directors", and then all directors are automatically included in the diplo group, and have whatever permissions that diplos have.

Something approximating "negative permissions" is possible in this model, too. Suppose you want to give all of the IT team except Acid mumble admin. In this case, you'd want a special-purpose group, call it "mumble.admin", and give it ACL rules "deny Acid; allow IT group".

I can maybe see a case for requiring this kind of indirection for every permission on every app, which would indeed introduce a notion of a "permission" into core. But I think that this sort of negative-permission case is probably pretty rare, so I'd rather not force every application+permission to use a layer of indirection like this.

**Comment by kiu** [comment]
@jboing

I am also worried that a system where you have inheritance and negative permissions will quickly evolve into an unmanageable nightmare, but I wouldn't agree with your conclusion.

The goal is to have a central system where all permissions/groups are managed in a single place using the same UI covering all services. This will make our life easier.

In your system, where applications need to be configured, we will run into a similar problem, in the nature of keeping all system in sync.
Lets use your example, there are groups brave, blue and fcs. Now imagine a new group "leet DI" is invented (and i believe this will happen a lot), someone will need to re-configure all services to reflect this change (ping, timer, mumble, wiki, jabber, ...). Even worse, all services will probably have different configuration mechanisms (text, database, json, whatever).

**Comment by jboning** [comment]
Revisiting this:

Over time the idea of permissions is growing on me. Here's how I feel right now:
- Each group has a set of privileges, which are strings.
- When an app asks for info on a character, core looks up all of the characters groups, collects all of the groups' privileges into a set, and returns to the app the ones beginning with that app's name followed by a dot. It's up to the app to set the actual form of the privileges. As in your example, jabber could have "jabber.ping" and timerboard could have "timerboard.add". Forums could have "forums.forum.(forumname).post".
- I'm still not a fan of permission inheritance between groups. I think that having group membership inheritance is about as powerful, but easier to understand.

**Comment by jboning** [comment]
Following up on discussion on jabber:
- @Acidity has convinced me that permission inheritance is reasonable. Each group can inherit permissions from one or more other groups.
- Individual users can be granted permissions also.
- Separately, we'll still plan on adding a group acl rule for referencing other groups.

**Comment by Acidity** [comment]
^I've assigned myself to this issue, hopefully I'll be able to start work on it soon.
