### ISSUE TITLE
Travis CI integration.

### ISSUE THREAD

**Issue by amcgregor** [bravecollective/core#20]
No, in this case "integration integration" is not a bad thing.

**Comment by lmorchard** [comment]
I've hooked up a dozen or so projects to Travis CI, so I might be able to help here. I can't find any tests for the app, though - am I missing something?

**Comment by amcgregor** [comment]
I'll get a basic '2+2=4' test suite added.  If you could do the Travis goodness (have a gander at some of marrow projects… WebCore itself uses Travis and shows how the tests work) that would be epic.

**Comment by amcgregor** [comment]
Travis CI integration is added.

For those wanting to write tests, follow the general guideline from the [WebCore tests](https://github.com/marrow/WebCore/tree/develop/tests).  Generally there isn't a need to test the actual web layer, so testing direct calls to controller methods is A-OK, though story-based integration tests would be nice, too.
