### ISSUE TITLE
Joinable groups

### ISSUE THREAD

**Issue by jboning** [bravecollective/core#225]
Groups should be configurable so that users can apply to them or just join directly. Since group ACLs currently always operate on characters, I'll talk about characters rather than users from here on.

---
##### 1: simple solution

Each group to have one big option for "group type", which can be set to "secret", "restricted", or "public". To add a character to a group (either when an admin approves a request, or when a character adds themself to a group), they are added to a trailing "grant character" rule. The major advantage of this solution is that it's dirt simple to implement; the major disadvantage is that there's no granularity around who can see or join a group.
##### 2: fancy solution

Have three separate sets of ACLs, one giving membership (as in the current system), one giving apply access, and one giving join access. This would let you create (for example) interest groups that only alliance members can freely join, or an alliedfc group that only blues can apply to. In this system, it's not clear what should happen when someone joins a group via apply access or join access, and then loses that permission.

Option A: When someone joins a group, it's "permanent", and they retain access even if they lose the ability to leave and reenter the group.

Option B: When someone joins a group, their membership is tied to their original entry method. Losing the ability to reenter or reapply means that they also lose their membership.

The choice of behaviour here will affect the implementation of group joining. For the first option, it could be implemented as in the simple solution above, by simply adding the character to the membership acl list. For the second option, we'll need to keep separate lists of characters who have joined or had applications approved.
##### 3: different fancy solution

Remain with one ACL, but instead of only grant and deny, add ruletypes for grant-apply and grant-join. Here's pseudocode for how that would behave:

```
# access levels are MEMBER > CAN_JOIN > CAN_APPLY > NONE
max_access = NONE
for rule in rules:
    if rule applies to character:
        if rule is deny:
            return max_access
        if rule is grant:
            return MEMBER
        if rule is grant-apply:
            max_access = max(max_access, CAN_APPLY)
        if rule is grant-join:
            max_access = max(max_access, CAN_JOIN)
if max_access >= CAN_JOIN and character has joined group:
    return MEMBER
if max_access >= CAN_APPLY and character has been approved for group:
    return MEMBER
return max_access
```

Options A and B apply here as well. This pseudocode assumes that membership is tied to original entry method, but the other way (having this simply add members to the group) is possible with only small modifications.

---

Thoughts? I'm learning toward solution 2 (I think granularity of visibility and application is needed, so 1 isn't good enough; between 2 and 3, I think 2 is clearer, though it requires more acl configuration and potentially some redundancy) and option B (I think automatically removing people from groups when they leave will be much safer than doing it manually; it may require some admin effort to re-add people to groups that we want them to remain in, but probably less effort than culling people who no longer belong).

**Comment by Acidity** [comment]
I agree with you, Solution 2, Option B seems to be the best choice to me as well.

**Comment by Acidity** [comment]
Resolved in feature/groups.
