### ISSUE TITLE
Dev setup docs, please!

### ISSUE THREAD

**Issue by lmorchard** [bravecollective/core#23]
Some dev setup docs would be much appreciated. I spent some time working through setting up a local dev instance of this stuff for myself under an Ubuntu 13.04 VM. But, I hit some bumps and finally stalled out. 

I tried starting from a fresh virtualenv and a `python setup.py develop`. These are some things I ran into:
- Just "requests" is listed in `setup.py`, but 2.0.0 conflicts with other dependencies. This seems fixed when I tweak it to `'requests==1.1.0'`
- A new version of `xmltodict` [seems to have been released tonight](https://github.com/martinblech/xmltodict/commit/3570aa1828a4ef8d563e98d530d20134428d4a76), and that started giving me `ImportError: No module named distribute_setup` errors on initial setup. Specifying `'xmltodict==0.7.0'` seems to have fixed that
- Installing `scrypt` from pypi seems to be broken, at least in my Ubuntu VM. It can't seem to find the `_scrypt` module. [Installing straight from BitBucket](https://pypi.python.org/pypi/scrypt/#installation) seems to have fixed this.
- Running `paster serve development.ini` then gave me an ImportError for `marrow.widgets`. Seemed like I fixed that by tracking down [the project on github](https://github.com/marrow/marrow.tags), and installing it from there.

Finally, I got some kind of server running. Then, the error in my browser looks something like `TypeError: __init__() got an unexpected keyword argument 'i18n'` at `Module marrow.templating.template.mako_:31 in get_template`.

So, I think I'll wave the white flag for now and take another crack at it tomorrow. Some tips in the meantime would be great. Thanks!

**Comment by amcgregor** [comment]
You'll need git-develop branch copies of marrow/marrow.templating (i18n support) and marrow/marrow.tags (widgets).

**Comment by lmorchard** [comment]
Ah hah, yup - getting the develop branch copy of marrow/marrow.templating appears to have resolved my i18n error and I see the pretty login screen. I see you updated README.textile too, so this issue is probably closed enough for now, thanks!
