### ISSUE TITLE
We need a way to manage working on two different releases at once.

### ISSUE THREAD

**Issue by Acidity** [bravecollective/core#235]
I.e. Working on 0.6.2 and 0.7 simultaneously. I propose we use develop for the changes we know are going to ship in the next version, while using a different branch (perhaps one named after the version such as v0.7) for longer terms merges.

**Comment by jboning** [comment]
http://nvie.com/posts/a-successful-git-branching-model/ was the original plan draleth had in place I think

**Comment by Acidity** [comment]
Resolved.
