### ISSUE TITLE
application-to-application grants

### ISSUE THREAD

**Issue by jboning** [bravecollective/core#244]
APIs make the world go round, but right now the only software in our little suite of tools that has an API is core itself. I'd like to have some standardized, centrally-mediated way of authorizing one app to access another.

I have some blurry ideas about how this might work but I'm too tired to clarify them at the moment, will try to elaborate more tomorrow or this weekend.

**Comment by Acidity** [comment]
I've actually been thinking about this a lot for the past month or so as well, and I definitely think it's something worth adding down the road. As I imagined it (albeit very vaguely), I thought that applications could declare to Core certain API calls that they'd make available to other applications and Core would have an availableAPICalls API call to let other applications know what they can use. All actual calls would still go through Core using the already submitted application keys. One of the problems, is how to determine which application gets access to which calls, but that's a topic I feel is best left for another issue.
