### ISSUE TITLE
Core doesn't like numeric character names

### ISSUE THREAD

**Issue by paxswill** [bravecollective/core#264]
> 22:59:30 paxswill: serinus_gareth: so< I think I have an idea of why the SF guy was having problems
> 22:59:54 paxswill: so the key is added just fine, but raises a ValidationError
> 23:01:06 17007870: hey guys, Serinus told me you guys can help me out with my problem. Is there anyone on atm?
> 23:02:09 paxswill: [here](https://github.com/bravecollective/core/blob/develop/brave/core/key/controller.py#L116), right after the key is saved to mongo, the characters are pulled, which [also triggers a save](https://github.com/bravecollective/core/blob/develop/brave/core/key/model.py#L140) (I'm operating under the assumption that basically only saves can raise ValidationErrors).
> 23:03:31 paxswill: Because his name can is entirely a number, (this is the stretch I'm not sure about), it gets [parsed as a number](https://github.com/bravecollective/core/blob/develop/brave/core/util/eve.py#L99) and then there's an attempt to [save it to a StringField](https://github.com/bravecollective/core/blob/develop/brave/core/character/model.py#L27)
> 23:03:42 paxswill: speak of the devil

Core assumes character names won't be numbers, when they can be (ex: [1700870](https://gate.eveonline.com/Profile/17007870), full specification on what a name can be [here](http://community.eveonline.com/support/policies/eve-user-policy/)). There's at least one [other place](https://github.com/bravecollective/core/blob/develop/brave/core/character/model.py#L34) where it makes that assumption as well.

For a solution, I'm thinking of killing the "smart" [`get`](https://github.com/bravecollective/core/blob/develop/brave/core/character/model.py#L32) method, and forcing queries to specify which attribute they're trying to query against. Then force all values being assigned to the [`name`](https://github.com/bravecollective/core/blob/develop/brave/core/character/model.py#L32) attribute to be strings. It feels a little hacky, and I'd really like to hear other ways to solve this.

**Comment by paxswill** [comment]
OK, digging through the MonoEngine documentation, and it looks like the [`clean`](http://docs.mongoengine.org/guide/document-instances.html#pre-save-data-validation-and-cleaning) method can be used to fix up the name attribute before validation occurs.

**Comment by paxswill** [comment]
Also, searching through GitHub suggests that the only place the "smart" `get` is used is [here](https://github.com/bravecollective/core/blob/f49a1c01127781bcfc11847f080527ed4e3687d1/brave/core/api/lookup.py#L37). [This line](https://github.com/bravecollective/core/blob/cc457916e6ac0cc5a49fbbc79d28c09e3425d5c9/brave/core/character/controller.py#L18) also calls the method, but it specifies the attribute to query explicitly.

**Comment by Acidity** [comment]
Resolved by #332.
