### ISSUE TITLE
Verify user email addresses.

### ISSUE THREAD

**Issue by Acidity** [bravecollective/core#290]
User email addresses should be verified (by sending a mail to them with a time-limited access code in it) when they create an account and when they change their email address. Unverified accounts should be unable to add API keys and to authorize applications, but _should_ be able to change their email address and to request that a new verification mail be sent (a hard limit of 1 mail per 15 minutes per person should be enforced). All existing accounts should be considered unverified, and require verification before they can add new keys and applications, but their existing authorized applications and API keys should be untouched.

**Comment by jboning** [comment]
Wait, is there code in for this?

**Comment by Acidity** [comment]
Closed as a duplicate of #3
