### ISSUE TITLE
Changing password fails (Internal Server Error)

### ISSUE THREAD

**Issue by xou** [bravecollective/core#298]
Changing the password on my account "fails:, the error message displayed is "Error sending data, please try again later...".

Looking at the data in the network inspector shows a 500 Internal Server Error.

Attempting to submit the password again leads to an "Token Expired" error. It is possible to login with the new password.

**Comment by Acidity** [comment]
I was unable to reproduce any issues with changing Core passwords, could you provide more information about the issue?

**Comment by xou** [comment]
What kind of info do you need? (I assume you are Acid Katelo in-game, i can send you more sensitive info via IGM?)

**Comment by Acidity** [comment]
Never send anything sensitive in game, (I really wish I could set my CSPA charge to 1 billion isk or something :/). You can send me a message on jabber (acid_katelo@bravecollective.com).

**Comment by jboning** [comment]
Closing since this seems stale--if this is still occurring or you have repro information, feel free to reopen.
