### ISSUE TITLE
Password complexity too high

### ISSUE THREAD

**Issue by xou** [bravecollective/core#299]
As an improvement, i would suggest lowering the password requirements, and specifying the exact rules the password has to conform to.

Both me and a friend have - independently - resorted to using one of our toon's names as the base for the password (out of frustration with bugs like #298 - and others which were present when i first signed up). I would assume other users do the same thing, and obviously such passwords can be quite easily guessed (especially in a case where a hacker has access to the DB, which would include the toon's names).

Not beeing able to remember my password before has led me, and my friend, to avoiding the brave services infrastructure alltogether.
I would propose switching to a simpler scheme - for example, minimum 8 characters + at least one upper/special char. This is what, for example, my email provider and my online banking require - and if it's good enough for them... ;)

(This is also true for external stuff like Mumble etc., i don't know what the requirements are there now, since, as stated above, i haven't been using those in a long time)

**Comment by Acidity** [comment]
"minimum 8 characters + at least one upper/special char."

Where exactly do those rules come from? They're entirely arbitrary, and provide 0 protection against bad passwords (for instance 'Password' would be acceptable under those rules). Also, an inability to use the password you use for your bank is definitely a good thing ;)

**Comment by xou** [comment]
9 chars then ;)? (sorry was busy and just reminded by the in-game mail, and no, that reddit thread wasn't made by me)

I agree though with the reasons stated in the reddit thread. You could enforce higher-complexity passwords on admin accounts, but there is little worth protecting in your average BNI account, except for maybe the API key. We assume there are Spais everywhere anyway. If someone want's to use "password" for it's account - well, it's their API key they might loose.

A focus should be ease of use, and apparently i'm not the only one complaining that the system does not provide this as much as it could :)

So i would propose
- store the complexity of the password in the DB, so you can enforce higher-complexity passwords for director-level accounts if you wish,
- reduce the required complexity to something with clearly specified rules, as suggested in the original post,
- give a password strength indicator when setting the password to warn users when they are using weak passwords

**Comment by Acidity** [comment]
`store the complexity of the password in the DB, so you can enforce higher-complexity passwords for director-level accounts if you wish`
 Very Very Bad idea. Storing the complexity allows an attacker who to restrict the possibilities of what the password could be, and speed up a brute force attempt substantially.

`reduce the required complexity to something with clearly specified rules, as suggested in the original post`
 Implementing arbitrary rules for passwords just because everyone else does isn't generally what I consider a good idea...

`give a password strength indicator when setting the password to warn users when they are using weak passwords`
Agreed

**Comment by xou** [comment]
> Implementing arbitrary rules for passwords just because everyone else does isn't generally what I consider a good idea...

True.

> Very Very Bad idea. Storing the complexity allows an attacker who to restrict the possibilities of what > the password could be, and speed up a brute force attempt substantially.

If this is a number from 1-4, that's like 2 bits of information the attacker knows ;) On the other hand, if you enforce a more complex password than the user is used to, the user might resort to something that can be more easily remembered (for example, i found my old password again - it was "ThisIsVerySecurePassword!12345" ;) )

I'm just thinking, if someone want's to use "A" as a password, what's the problem? The user should be warned that this is extremely insecure, but it's their API key they might loose.

Anyway, this is now being discussed by a wider audience on [reddit](http://www.reddit.com/r/Bravenewbies/comments/2dyz2w/drama_cyno_the_complex_password_policy_is/) and the [forums](https://forums.braveineve.com/it/53f3b28ab9e8000bbf16ba99). I guess it's better to keep the discussion there then :)

**Comment by Acidity** [comment]
Their API key, and access to our wiki, and forums, and mumble, and jabber.

**Comment by xou** [comment]
Yeah but if someone wanted that, they could just create a new alt and join brave :)

**Comment by Acidity** [comment]
Just because recruiting doesn't have security does not mean that IT should design our systems without security; if in the future recruiting were to be more stringent, we don't want to have to redesign our entire security model.

**Comment by Acidity** [comment]
Resolved by #329.
