### ISSUE TITLE
Check for local networks in core.authorize is easily bypassed

### ISSUE THREAD

**Issue by drakedevel** [bravecollective/core#341]
In brave/core/api/core.py:80, there's a check that looks like this:

```
if not boolean(config.get('debug', False)) and (success.host in ('localhost', '127.0.0.1') or \
    success.host.startswith('192.168.') or \
    success.host.startswith('10.')):
    response.status_int = 400
```

If this check worked, it would make developing new applications somewhat annoying. However, it is readily bypassed by using any domain that resolves to 127.0.0.1. e.g. `localhost.hax.so`. It also misses the `172.16.0.0/16` and `169.254.0.0/16` local reserved blocks. 

Attempting to fix it by checking whether the domain _resolves_ to one of these networks then means that it can be bypassed by using `/etc/hosts` on the local system.

As such the check should probably just be removed. What is it attempting to prevent?

**Comment by jboning** [comment]
I don't know the history of this. Maybe @amcgregor can say?

**Comment by curiousstranger** [comment]
I'll chime in here and say it should just be removed, since as pointed out above, it makes development really annoying.

**Comment by jboning** [comment]
I think it will be okay to remove this, I'll want to spend a bit of time thinking just to make sure. The change is easy enough so whenever I find next find some time to spend on core!
