### ISSUE TITLE
 ⇝ KeyError: u'core.recommended_key_kind' when trying to open the Page to add an API to an Account

### ISSUE THREAD

**Issue by MaxRink** [bravecollective/core#342]
Im getting an Error when trying to load the Page. Dump: http://pastebin.com/GA6KBkGC

What is my Mistake?

**Comment by Acidity** [comment]
You're missing the config value core.recommended_key_kind from your config.

**Comment by jboning** [comment]
Closing as this looks like it was just a config issue in dev. @MaxRink if you see problems feel free to reopen or ask for help on jabber!
