### ISSUE TITLE
Core should be aware of coalition

### ISSUE THREAD

**Issue by kiu** [bravecollective/core#390]
[This feature request would be a temporary solution until group/acl inheritance is implemented.]

We have many groups which use an alliance list to exclude people outside of the coalition to gain access to a group. Everytime a new alliance is added to HERO all groups need to be touched and kept in sync, this is error prone.

Core groups should have an Coalition filter which can be applied as any other filter mechanism. As this is probably a temporary feature, it would be good enough to only have a hardcoded list of HERO somewhere and not a fully fledged UI for configuration.

Allow/Deny if is/not member of HERO.

**Comment by jboning** [comment]
I landed the ACL rule to control group access based on membership of other groups. Since it sounds like this was a stopgap request, can we close this?

**Comment by jboning** [comment]
(assuming yes)

**Comment by kiu** [comment]
yes. sorry being late to the party.
