### ISSUE TITLE
Core should update corp and alliance tickers when it pulls api keys

### ISSUE THREAD

**Issue by kiu** [bravecollective/core#391]
Everytime API keys are pulled from CCP, core should store corp and alliance tickers if they are missing in the dataset.

**Comment by jboning** [comment]
kiu wrote a script to pull in tickers, need to figure out where the best place to integrate this is: https://gist.github.com/kiu/f834db78719639d00818

**Comment by kiu** [comment]
Corp tickers could be updated everytime we pull api keys https://github.com/bravecollective/core/blob/develop/brave/core/key/model.py#L96

For alliance tickers (as the download from CCP is 2MB) it would be nice to have a cached version somewhere which gets updated every 24h or so.

**Comment by jboning** [comment]
Corp and alliance tickers are immutable, right? So we could update only on demand when we see a new corp/alliance without problems?

**Comment by jboning** [comment]
Alliance tickers are filled by the EVEAlliance.populate() call. I just committed 1d50ee35186d58a94aff1cb7aee6c2b3bf55fed4 which loads corp tickers lazily; that won't let you search by ticker, but we'll at least be able to show it in the UI.
