### ISSUE TITLE
Characters in ACL should show corp/alliance ticker

### ISSUE THREAD

**Issue by kiu** [bravecollective/core#394]
The ACL rules for adding individual characters to a group, should show [corp] < alliance > behind the character name or even better have that as a mouseover overlay.

**Comment by jboning** [comment]
![](https://dl.dropbox.com/s/lv72vvpjuzp6n2c/Screenshot%202015-03-08%2001.13.21.png?dl=0)

I'm not sure if I love this; it feels pretty space-inefficient, but I'm not sure that hiding it behind a mouseover is very useful. I'll push it anyway, easy enough to change in the future.
