### ISSUE TITLE
CorporationTitles consisting of numbers only breaks key parsing

### ISSUE THREAD

**Issue by kiu** [bravecollective/core#396]
< row titleID="512" titleName="2" / >

> > > u.credentials.first().pull()
> > > 2015-03-14 15:08:38,585 INFO  [brave.core.util.eve] Making query to char.CharacterSheet for key ID xxxxxx.
> > > 2015-03-14 15:08:38,585 INFO  [requests.packages.urllib3.connectionpool] Starting new HTTPS connection (1): api.eveonline.com
> > > Traceback (most recent call last):
> > >   File "<console>", line 1, in <module>
> > >   File "/home/core/src/brave/core/key/model.py", line 265, in pull
> > >     character = self.pull_character(char)
> > >   File "/home/core/src/brave/core/key/model.py", line 147, in pull_character
> > >     char.titles = [strip_tags(i.titleName) for i in info.corporationTitles.row] if 'corporationTitles' in info else []
> > >   File "/home/core/src/brave/core/util/**init**.py", line 30, in strip_tags
> > >     txt = re.sub('<[^>]+>', '', html)
> > >   File "/home/core/lib/python2.7/re.py", line 151, in sub
> > >     return _compile(pattern, flags).sub(repl, string, count)
> > > TypeError: expected string or buffer

**Comment by jboning** [comment]
Yeah, this is another example of the general problem that the api layer tries to guess types based on values. I'm going to rip the current API stuff out and replace it with evelink when I get the chance.

**Comment by kiu** [comment]
Temporary fix

core/util/**init**.py

def strip_tags(html):
    if isinstance(html, int):
        html = str(html)
    if isinstance(html, float):
        html = str(html)
    txt = re.sub('<[^>]+>', '', html)
    return re.sub('\s+', ' ', txt)

**Comment by jboning** [comment]
https://github.com/bravecollective/core/compare/develop...jboning:evelink has a real fix for this, I was going to let it bake on sound's instance for a few days before landing

**Comment by kiu** [comment]
Awesome! But we needed a fix now as some of our groups started to break :)
