### ISSUE TITLE
Account Management

### ISSUE THREAD

**Issue by amcgregor** [bravecollective/core#4]
- [x] Account management form.
- [x] General attribute update action.
- [x] Password change action.
- [x] Confirmation e-mail.
- [x] Account deletion action.

**Comment by lmorchard** [comment]
FWIW: Can't say I'm going to get anywhere fast because I've been crazy busy for a month now, but... I've been working on a simple password change form as my intro into the framework & project.

**Comment by ghost** [comment]
Make password reset link work

**Comment by Acidity** [comment]
Working on this issue at the moment.

**Comment by Acidity** [comment]
Could you provide more detail on what you want from the Account management form and General attribute update action?
