### ISSUE TITLE
password recovery e-mail is wrong

### ISSUE THREAD

**Issue by TriumvirateRhade** [bravecollective/core#401]
We're sorry to hear you're having trouble signing into the Brave Collective core services site.

You can use this link to reset your password. 

the "this link" links to:
http://email.braveineve.com/c/eJxljsEKwjAQRL8mPZZNsmm3hxwE8Tdkm6w2aK3EWPDvjYKgCHMY5g3DRD9ClK5J3oB2GgzpHtFSq0H31FpABwphzLxKusgqbVjmZvLcdYMDDhGAe30QjJocIh8ijwKWm7OfSrnelN0os6sKS5b2d6amHMJyv5TqsoRllazsxz32J3kouzUDwWuaiAbsTX1EynQyczpXWnK6z2vKXCRPHEUZh3B8wffR7P8KX_gJW6dP2g

this is not the correct recovery url

**Comment by kiu** [comment]
Correct. The mail contains two links, the latter is correct. I need to remove the first one...

**Comment by bargulg** [comment]
Seems like the problem is bad configuration of SMTP server, which thinks that link is an attachment and replaces it

**Comment by bargulg** [comment]
@kiu  fixed configuration. link is still replaced, but now it's replaced with one that actually works, so let's call it a workaround and keep this issue open until we get rid of the workaround
