### ISSUE TITLE
Adding yourself as admin

### ISSUE THREAD

**Issue by orbitroom** [bravecollective/core#402]
> > > from brave.core.account.model import User
> > > from brave.core.character.model import EVECharacter
> > > from brave.core.permission.model import Permission, WildcardPermission
> > > u = User.objects(username=gopro)[0]
> > > Traceback (most recent call last):
> > >   File "<console>", line 1, in <module>
> > > NameError: name 'gopro' is not defined

**Comment by jboning** [comment]
the username must be surrounded with quotes, like `username="gopro"`
