### ISSUE TITLE
Adding Application Documentation

### ISSUE THREAD

**Issue by orbitroom** [bravecollective/core#405]
Need to add more documentation on adding an application with a emphasis on creating a ECDSA key. My team and I have yet to figure it out.

**Comment by mglinski** [comment]
[You can look at this example application on generating an ECDSA key properly.](https://github.com/bravecollective/core-api-hello-world)

**Comment by orbitroom** [comment]
alright after looking at the example Ive come to the conclusion that im missing the core key? the development.ini never had such a thing but the test.ini does? what is the difference in local.ini and the production keys?

**Comment by mglinski** [comment]
The Core key is the same as an application key, You need to supply a HEX encoded private/public ECDSA keypair into the development.ini file. You can use that example app to load all the dependencies you need to generate that key. Then you just copy+paste in.
