### ISSUE TITLE
Profile and Help is broken

### ISSUE THREAD

**Issue by kiu** [bravecollective/core#421]
Using the dropdown menu to select Profile (https://core.braveineve.com/account/), leads to a 400 Bad Request.

Using the dropdown menu to select Help (https://core.braveineve.com/help), leads to a 404 Not Found.

Either show something useful or remove this option.

http://i.imgur.com/WgnHWwA.png

**Comment by bargulg** [comment]
profile is already fixed in https://github.com/bravecollective/core/commit/651cc3d5e5fa3f71051748126abc89ebc818bceb

**Comment by bargulg** [comment]
link to help page commented out for now, will add help page later
