### ISSUE TITLE
Support for enhanced api key mask

### ISSUE THREAD

**Issue by kiu** [bravecollective/core#423]
CCP introduced additional capabilities to the API key mask. I assume this works fine for Group ACLs, but when showing key capabilities under https://core.braveineve.com/key/<keyid> the new fields are missing.

http://i.imgur.com/X746NkS.png

New fields are: ChatChannels, Clones, Bookmarks, Skills

**Comment by bargulg** [comment]
fixed in https://github.com/bravecollective/core/commit/68033b866a738ea619ed973accb47a55fc679e8d
