### ISSUE TITLE
Urlencoding in dashboard for corp/alliance links

### ISSUE THREAD

**Issue by kiu** [bravecollective/core#425]
We encode urls in the dashboard view like this:

https://gate.eveonline.com/Corporation/Brave+Newbies+Inc.
https://gate.eveonline.com/Alliance/Brave+Collective

The IIS gate server does not like this.

**Comment by bargulg** [comment]
fixed in https://github.com/bravecollective/core/commit/522626b531bfc4b321c1df0f10f47a922126c39d
