### ISSUE TITLE
docker image?

### ISSUE THREAD

**Issue by raykai** [bravecollective/core#436]
would be nice to have this in a docker image. It would be a lot simpler for people to use to use.

Even more, if we could get all of the brave apps in a docker image and ready to go, now that would be brave :P

**Comment by raykai** [comment]
or have it in a VM image.

**Comment by bargulg** [comment]
You're right. Having all the brave apps in a docker image would be very brave: https://thehftguy.com/2016/11/01/docker-in-production-an-history-of-failure/
VM image would be nice, but I'm afraid that would take so much maintenance it's not worth it for an organization that's not making profit out of it.
