### ISSUE TITLE
Account Registration Hangs when invalid email is input and submitted

### ISSUE THREAD

**Issue by StupidGenius** [bravecollective/core#44]
Actual:
![bcs_register_hang](https://f.cloud.github.com/assets/292108/2051978/73287c38-8a90-11e3-9d76-0ecbe5e81eed.JPG)
On the Sign-Up form.
If a user enters an invalid email like "SomeText" but all their other information is correct, then when they click Sign-Up, the progress wheel is displayed indefinitely.

The Email field only complains it is invalid when selected, but if other fields are selected, then there is no indication.

![bcs_register](https://f.cloud.github.com/assets/292108/2051987/866ff4f6-8a90-11e3-9b4a-aa40a12fd453.JPG)
![bcs_register_email_field_selected](https://f.cloud.github.com/assets/292108/2051989/89213160-8a90-11e3-8a98-ce8e0ba147b3.JPG)

Expected:
Should validate the email field before attempting account creation.

**Comment by ghost** [comment]
+1

**Comment by Acidity** [comment]
Resolved by PR #107.
