### ISSUE TITLE
Handle not having any characters loaded.

### ISSUE THREAD

**Issue by amcgregor** [bravecollective/core#47]
IndexError: list index out of range

Module brave.core.controller:56 in get

**Comment by ghost** [comment]
sample error message:  

Authorization for this application is on a per-character basis. Your Core account does not currently have any characters added, so you cannot yet authorize this application. Go `<a href="https://core.bravecollective.net/key/">here</a>`, click Add Key, and follow the instructions to add an API key for an appropriate character. Once Core knows about your character, return here and try authorizing again.
