### ISSUE TITLE
Mumber Char wrong / Unable to de-authroize Mumble access

### ISSUE THREAD

**Issue by LiberoAnon** [bravecollective/core#48]
When I authorize Mumble it auto-populates an incorrect pilot name and there is no option to change it anywhere.  The API key was created only for 'Libero Anon' but the pilot name that shows up is 'Erin Peteros'.  Furthermore I am unable to de-authorize mumble via the applications page in core.  I click the red 'x' and it just doesn't do anything.

**Comment by amcgregor** [comment]
I'm working on this feature right now.

**Comment by amcgregor** [comment]
The red X button should now correctly de-authorize an application.

You can select a non-default character using the pop-up arrow to the right-hand side of the 'Authorize' button.  You can also change which character is default by clicking the right-hand star on the character list.
