### ISSUE TITLE
Browser doesn't store login credentials

### ISSUE THREAD

**Issue by kiu** [bravecollective/core#53]
1. Go to https://core.bravecollective.net/account/authenticate
2. Enter your credentials and login

Expected
Browser asks to store password credentials

Actual
Browser ignores login form

**Comment by amcgregor** [comment]
This depends heavily on the browser used.  For example, the following video indicates pretty clearly that it's remembering my password.

> http://f.cl.ly/items/2r0r402E1A2e3N2X092E/auth-mumble-720.mov

**Comment by kiu** [comment]
On Firefox 26.0 (win+ubuntu) and Chromium 32.x it doesnt...

**Comment by amcgregor** [comment]
The field is named `password`, and it has a valid (if hidden) actual form submit button.  Could you test if pressing enter in the form saves the password, vs. clicking on the authenticate button?

**Comment by kiu** [comment]
That did the trick. Hitting enter enabled the save password functionality.
