### ISSUE TITLE
Add helpful 404 and 500 handler pages.

### ISSUE THREAD

**Issue by kiu** [bravecollective/core#54]
Some links are broken:

https://core.bravecollective.net/group/ --> 404
https://core.bravecollective.net/admin/ --> 404
All apps listed under https://core.bravecollective.net/application/browse/ --> 404
Profile button in drop down
https://core.bravecollective.net/help --> 404

**Comment by ghost** [comment]
i disagree they should be disabled. i think we should have a really awesome 404 page though to replace it. and if possible this should be displayed with the Core template so they can just click another link.

**Comment by ghost** [comment]
The wormhole closes behind you soundlessly. You check your inventory. Looks like your exotic dancers hid all your probes... You can `<a href="/">pod yourself and try something different</a>` or wait and see what happens.

**Comment by amcgregor** [comment]
+1 on the 404 page idea.  Updating ticket mandate.

**Comment by kiu** [comment]
I appreciate nicer 404 pages, but actually my intend was different one.

From a user experience perspective, having links on a page which are known to cause a 404 for all users in 100% of all cases is contra productive.
- It confuses new users (why doesn't this work? Is it my fault? Which links am i supposed to click?)
- Once the link has actual content behind it, users already learned to never click on them, so they wont be able to discover new functionality on their own.

**Comment by ghost** [comment]
via [w3.org](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html):  

> Response status codes beginning with the digit "5" indicate cases in which the server is aware that it has erred or is incapable of performing the request
> 501 Not Implemented
> The server does not support the functionality required to fulfill the request.

I think this would be an appropriate code for the as-yet-unimplemented pages, the 501 template can explain "This feature is yet to be coded"

**Comment by kougeki-kage** [comment]
I derped with git, so its in two commits, but I was able to write up a basic 'not implemented' page and have the links referenced above display that page instead of 404. I was planning on trying to work in a custom 404 page that you would go to from any bad link, but haven't figured out how to do that yet. Feedback appreciated 7o
