### ISSUE TITLE
Auth doesnt work in IGB

### ISSUE THREAD

**Issue by kiu** [bravecollective/core#56]
Go to https://core.bravecollective.net/account/ in the IGB.
Page without CSS is displayed.
1. Enter credentials
2. Cick Sign In

Expected
Login works and browser is redirected content

Actual
Browser stays on page. No action

From my point of view, IGB support is a MVP feature. Future apps which use IGB functionality need to be able to use auth.

**Comment by bargulg** [comment]
IGB is deprecated and will be removed this year, so we can close this issue
