### ISSUE TITLE
Implement password recovery.

### ISSUE THREAD

**Issue by kiu** [bravecollective/core#57]
1. Go to https://core.bravecollective.net/account/
2. Click Password Recovery

Expected
Some kind of password recovery functionality. E.g. email address input field.

Actual
Nothing happens

Comment
Due to the fact that https://github.com/bravecollective/core/issues/53
it is even more important to be able to recover your password.

**Comment by ghost** [comment]
+1

**Comment by jboning** [comment]
This issue can be closed now, right? :D

**Comment by Acidity** [comment]
Tested by Khartana, and live on SOUND's Core deployment. Resolved by PR #98.
