### ISSUE TITLE
Close duplicate accounts for Captain Nuchar Khardula

### ISSUE THREAD

**Issue by ghost** [bravecollective/core#60]
Account names davebunting / Captain Nuchar Khardula

no preference on which to keep given

**Comment by amcgregor** [comment]
I've kept `davebunting` and merged the other into it.  The API key on the account appears to be invalid; he'll want to remove it, delete it from EVE's API support site, and create a brand new one.

**Comment by DaveBunting** [comment]
Hi guys, thanks for your help! I've followed the above instructions, however my character still hasnt loaded onto core services. Do i have to wait quite a while for the new api to register?

**Comment by ghost** [comment]
nope it is generally instant. most likely you added a 0 permissions api
key. please try deleting your api keys from Core at
https://core.bravecollective.net/key/

then use this link to pre-select the appropriate permissions on a new API
key:
http://community.eveonline.com/support/api-key/CreatePredefined?accessMask=8921088

confirm that at least the first three items in Public Information are
checked, then click 'Submit' on CCP's page

finally paste the new keyid/vcode details into Core at
https://core.bravecollective.net/key/

gl!

**Comment by DaveBunting** [comment]
Hi, ive done the above again, the access mask is 8921088 (i believe this is what is needed from ticking the appropriate boxes), but the character is still not loading.

**Comment by DaveBunting** [comment]
Would it be better if the whole profile was cancelled and i just start again?
