### ISSUE TITLE
multiple accts (im blind to bold text)

### ISSUE THREAD

**Issue by rainingbacon** [bravecollective/core#73]
hello, i broke all the things and created two accounts because i suck at words. can you please merge the username: wad    with the username: rainingbacon    ?     ideally i would be "rainingbacon" as that is my char name.

thanks for putting up with me

**Comment by amcgregor** [comment]
Having two accounts isn't actually the issue in your case, though I have taken the precaution of merging `wad` into `rainingbacon`.  Your access key mask is zero, which means Core won't be able to ask the key what characters it provides access to.  You'll have to delete the key from EVE's support site and Core, generate a brand new key and _be sure_ the key has a mask allowing Public character information access.
