### ISSUE TITLE
Provide help on how to generate the ECDSA keys needed to register an application

### ISSUE THREAD

**Issue by kiu** [bravecollective/core#76]
- Link to the python script for key generation
- Link to script for classic openssl users (is that correct?)
  # !/bin/sh
  
  openssl ecparam -out brave.key.pem -name prime256v1 -genkey
  openssl ec -out brave.pub.pem -inform PEM -in brave.key.pem -pubout
- Describe how the upload format exactly looks like. Full PEM incl headers?

**Comment by kiu** [comment]
duplicate

**Comment by kiu** [comment]
My mistake, this wasnt a duplicate. The referred item describes EVE API Keys rather than CORE Keys.

**Comment by amcgregor** [comment]
``` python
#!/bin/env python

from __future__ import print_funciton

from hashlib import sha256
from ecdsa.keys import SigningKey
from ecdsa.curves import NIST256p

private = SigningKey.generate(NIST256p, hashfunc=sha256)

print("Private Key:", private.to_string().encode('hex'))
print("Public Key:", private.get_verifying_key().to_string().encode('hex'))
```

Upload format is the hex returned by the public component above.  In the Python project INI files you would store the private key generated above and the public key generated by Core when you register your application.
