### ISSUE TITLE
Track character from IGB for use as default during authorization.

### ISSUE THREAD

**Issue by sythe7448** [bravecollective/core#79]
Use IGB character ID during authorization

**Comment by ghost** [comment]
use it for what? you can't trust it, i can craft an http request that pretends to be a request from your character using the IGB

**Comment by amcgregor** [comment]
It'd be used as a hint for the authorization step, selecting your current character as the Authorize button's default character.

**Comment by bargulg** [comment]
IGB is deprecated and will be removed this year, so we can close this issue
