### ISSUE TITLE
Administrative management of keys.

### ISSUE THREAD

**Issue by amcgregor** [bravecollective/core#8]

**Comment by Byetsniv** [comment]
Ok, got my local copy of core running. Created a new account, logged in, and added an API key, so it seems to work currently.

Is there a more thorough description of what "Administrative management" means, or what features are required?

I'm guessing maybe something where "admins" can look at things like "Who has/doesn't have keys that can do X", is that right?

Or is it more for something that the users can see, for example in the current view you can't see what the given key grants access to, is that something to be shown? Maybe revocation dates and things as well?

**Comment by Acidity** [comment]
Resolved by #219.
