### ISSUE TITLE
I changed my name from Estson AngelWolf to my alt name Curtis Huren who is not in brave. 

### ISSUE THREAD

**Issue by EstsonAngelWolf** [bravecollective/core#80]
I can not access mumble now.

**Comment by ghost** [comment]
Did you actually get CCP to change your character's name from Estson AngelWolf to Curtis Huren?

Or do you mean you are trying to log in to mumble with a non-brave character?

Only BRAVE members are allowed in mumble.

**Comment by ghost** [comment]
If you want to switch it back simply de-authorize mumble at https://core.bravecollective.net/application/ and then re-authenticate with your BRAVE character at https://manage.mumble.bravecollective.net
