### ISSUE TITLE
Mumble authentication/authorization issue

### ISSUE THREAD

**Issue by karoushi** [bravecollective/core#83]
I have not been able to authenticate on the Mumble server since I joined the corp last night. I have in that time recreated API keys three times. I tried copy & pasting my password and using two enters, then one enter. I tried manually entering the password. I receive two green check marks each time, but still get "wrong certificate or password" when attempting to log in.

About an hour ago I cleared the authorized mumble app from my list. Clicking "authorize" from the apps list does nothing, and resetting my Mumble password also does nothing. I cannot get Mumble back in the list of authorized apps.

Hoping for some guidance.

Thanks!

**Comment by TriumvirateRhade** [comment]
Confirmed as having been able to get on Mumble.
