### ISSUE TITLE
Corp Room Mispelled 

### ISSUE THREAD

**Issue by StupidGenius** [bravecollective/core#84]
Our corp, Alea Iacta Est Universal, are unable to access our corp's room in Mumble. 

We assume this is due to the room being misspelled as " Alea Lacta Est Universal" (Notice the L should be an I )

![alea iacta est universal](https://f.cloud.github.com/assets/292108/2133495/e03e978e-92c5-11e3-97b5-4297faf70517.JPG)

Thanks,
-Stu

**Comment by TriumvirateRhade** [comment]
This appears to be resolved, saw some notes on it on Jabber too. And there's people in the channel now.
