### ISSUE TITLE
Key pulling chokes on characters not in any alliance.

### ISSUE THREAD

**Issue by lizthegrey** [bravecollective/core#89]
> > > key.pull()
> > > 2014-02-20 17:09:05,268 INFO  [brave.core.util.eve] Returning cached result of account.APIKeyInfo for key ID 2866937.
> > > 2014-02-20 17:09:05,269 INFO  [brave.core.key.model] pull_full
> > > 2014-02-20 17:09:05,271 INFO  [brave.core.util.eve] Making query to char.CharacterSheet for key ID 2866937.
> > > 2014-02-20 17:09:05,320 INFO  [requests.packages.urllib3.connectionpool] Starting new HTTPS connection (1): api.eveonline.com
> > > 2014-02-20 17:09:07,675 INFO  [brave.core.key.model] pull_full
> > > 2014-02-20 17:09:07,677 INFO  [brave.core.util.eve] Making query to char.CharacterSheet for key ID 2866937.
> > > 2014-02-20 17:09:07,678 INFO  [requests.packages.urllib3.connectionpool] Starting new HTTPS connection (1): api.eveonline.com
> > > Traceback (most recent call last):
> > >   File "<console>", line 1, in <module>
> > >   File "/home/elizabeth/auth/core/brave/core/key/model.py", line 185, in pull
> > >     implementation(char)
> > >   File "/home/elizabeth/auth/core/brave/core/key/model.py", line 143, in pull_full
> > >     char, corporation, alliance = self.pull_minimal(info)
> > >   File "/home/elizabeth/auth/core/brave/core/key/model.py", line 89, in pull_minimal
> > >     corporation, alliance = self.get_membership(info)
> > >   File "/home/elizabeth/auth/core/brave/core/key/model.py", line 60, in get_membership
> > >     ) if 'allianceID' in info else (None, False)
> > >   File "/home/elizabeth/auth/lib/python2.7/site-packages/mongoengine-0.8.7-py2.7.egg/mongoengine/queryset/base.py", line 248, in get_or_create
> > >     doc.save(write_concern=write_concern)
> > >   File "/home/elizabeth/auth/lib/python2.7/site-packages/mongoengine-0.8.7-py2.7.egg/mongoengine/document.py", line 224, in save
> > >     self.validate(clean=clean)
> > >   File "/home/elizabeth/auth/lib/python2.7/site-packages/mongoengine-0.8.7-py2.7.egg/mongoengine/base/document.py", line 323, in validate
> > >     raise ValidationError(message, errors=errors)
> > > ValidationError: ValidationError (EVEEntity.EVEAlliance:None) (StringField only accepts string values: ['name'])

**Comment by lizthegrey** [comment]
Interesting:

> > > key.pull_minimal(r.characters.row[1])
> > > (EVECharacter(530668f02201f2538ce9f223, 732146811, "Sharidon"), EVECorporation(53065b172201f2538ce9f222, 299337873, "KVA Noble Inc."), None)
> > > 
> > > key.pull_full(r.characters.row[1])
> > > 2014-02-20 20:44:00,029 INFO  [brave.core.key.model] pull_full
> > > 2014-02-20 20:44:00,032 INFO  [brave.core.util.eve] Making query to char.CharacterSheet for key ID 2866937.
> > > 2014-02-20 20:44:00,032 INFO  [requests.packages.urllib3.connectionpool] Starting new HTTPS connection (1): api.eveonline.com
> > > Traceback (most recent call last):
> > >   File "<console>", line 1, in <module>
> > >   File "/home/elizabeth/auth/core/brave/core/key/model.py", line 143, in pull_full
> > >     char, corporation, alliance = self.pull_minimal(info)
> > >   File "/home/elizabeth/auth/core/brave/core/key/model.py", line 89, in pull_minimal
> > >     corporation, alliance = self.get_membership(info)
> > >   File "/home/elizabeth/auth/core/brave/core/key/model.py", line 60, in get_membership
> > >     ) if 'allianceID' in info else (None, False)
> > >   File "/home/elizabeth/auth/lib/python2.7/site-packages/mongoengine-0.8.7-py2.7.egg/mongoengine/queryset/base.py", line 248, in get_or_create
> > >     doc.save(write_concern=write_concern)
> > >   File "/home/elizabeth/auth/lib/python2.7/site-packages/mongoengine-0.8.7-py2.7.egg/mongoengine/document.py", line 224, in save
> > >     self.validate(clean=clean)
> > >   File "/home/elizabeth/auth/lib/python2.7/site-packages/mongoengine-0.8.7-py2.7.egg/mongoengine/base/document.py", line 323, in validate
> > >     raise ValidationError(message, errors=errors)
> > > ValidationError: ValidationError (EVEEntity.EVEAlliance:None) (StringField only accepts string values: ['name'])

**Comment by lizthegrey** [comment]
Aha, this is happening because for some reason the corp in question has an allianceID of 0 rather than no allianceID.

https://gate.eveonline.com/Corporation/KVA%20Noble%20Inc._ is the corp in question.

**Comment by amcgregor** [comment]
Thanks, CCP!  :disappointed:

**Comment by lizthegrey** [comment]
Simple patch is to replace the check for "if allianceID in info" with "if (allianceID in info and info.allianceID != 0)" at brave/core/key/model.py:60

**Comment by amcgregor** [comment]
Done and done, though I'll simply check against falsy; zero, None (JSON null), etc. are all invalid and falsy.
