### ISSUE TITLE
Need to change my Core Auth and I screwed up

### ISSUE THREAD

**Issue by SIthen** [bravecollective/core#90]
So I joined brave with my alt first (Sypher22), created a core account, registered for mumble etc. etc. 

Then I joined with my main (Sithen). I want to have Sypher22 leave BNI and register everything under Sithen instead. STUPIDLY I added Sithen's API to Sypher's CORE account thinking I could change the Mumble registration to Sithen.... but it doesn't seem to work that way.

Now I'm screwed, I can't register Sithen to another CORE Auth account...

Please help.

Thank you,
Sithen

**Comment by TriumvirateRhade** [comment]
This was solved ingame in Brave IT channel
