### ISSUE TITLE
Attempting to authorize fails if no characters are associated with an account

### ISSUE THREAD

**Issue by lizthegrey** [bravecollective/core#91]
[Sat Feb 22 09:11:22 2014] [error] [client 80.4.101.221] File '/var/www/auth/install/core/brave/core/controller.py', line 56 in get
[Sat Feb 22 09:11:22 2014] [error] [client 80.4.101.221]   default = u.primary or characters[0]
[Sat Feb 22 09:11:22 2014] [error] [client 80.4.101.221] IndexError: list index out of range

Fix: bounce the user to the keys/characters page if there is no character on file.

**Comment by sythe7448** [comment]
Issue #47 already describes this issue closing this ticket.
