### ISSUE TITLE
"Start Discussion" UI is pessimal

### ISSUE THREAD

**Issue by elly** [bravecollective/core#93]
The UI for "start discussion" looks like this:

![2014-02-26-152508_1366x768_scrot](https://f.cloud.github.com/assets/218734/2275163/af9dfe9c-9f24-11e3-9a96-fcb1af18efa8.png)

Specifically, the top "Start Discussion" button means "actually post", while the bottom one means "hide the post UI, even if you've typed something"; since there's no auto-refresh, the second one tricked me into hitting refresh, hoping to see my new post, thus losing my actual post text.

Ideally the two buttons should look somehow visually distinct, or the top button should be green and say "Post" and the bottom one should be like "[Show|Hide] Post Editor" or something.

**Comment by lizthegrey** [comment]
This bug needs to be cloned to forums project instead.

**Comment by amcgregor** [comment]
Closing as invalid; issue recreated [on the Forums issue tracker](/bravecollective/forums/issues/44).
