### ISSUE TITLE
So I registered my main account but then my password manager messed up

### ISSUE THREAD

**Issue by CzarK** [bravecollective/core#96]
And the reset password link for core doesn't work.
And I cant get the webjabber to work.
And the Brave It Team ingame channel is invite only.

I broke the rules and made another account to hopefully fix it or find and answer but once I logged in, it wouldn't actually let me register.
So I clicked on the help link and that 404'd.

Plz Hlp. 
in game name is Czar Vilinous

**Comment by CzarK** [comment]
Being helped. I need to learn to follow instructions better.

**Comment by amcgregor** [comment]
Merged; active account is now CzarK.  Apologies for the delay; hectic week!
