### ISSUE TITLE
Can't Login to Mumble

### ISSUE THREAD

**Issue by AxlotlTheNewt** [bravecollective/core#97]
I'm wondering/suspecting it's because I (accidentally) creaded a core account with an apostrophe in the username. Oops/help?

It's not password, I've tried like mazillion of those. My character shows up with a mumble enabled, so that shouldn't be it...

Thanks in advance, Axlotl D'Newt

**Comment by TriumvirateRhade** [comment]
I believe this was resolved, or am I confusing you with someone else?
